import Navbar from './Navbar';
import './globals.css';
import { Inter, Open_Sans, Playfair_Display } from 'next/font/google';

export const playfair = Playfair_Display({
	subsets: ['latin'],
});
const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={openSans.className}>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
